### ISSUE TITLE
Variable_selection errors

### ISSUE THREAD

**Issue by JRSlotman** [dhopp1/nowcastLSTM#12]
Hi Daniel,

I keep getting the following errors when running the variable_selection, regardless of the configuration of the function parameters (init_test_size, n_fold, etc). 
`C:\Users\...\AppData\Local\r-miniconda\lib\site-packages\nowcast_lstm\data_setup.py:203: RuntimeWarning: Mean of empty slice
  rawdata[col] = rawdata[col].fillna(fill_na_func(fill_na_df[col]))
multivariate stage: 0 / 179 columns
...
multivariate stage: 17 / 179 columns
Error: IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed`

I used to be able to run the function on smaller country data with the following parameters: init_test_size = 0.3,                                    n_fold = 2,  initial_ordering = "feature_contribution", pub_lags = -1. Now I'm trying to change the workflow to wider panel data, as you suggested. Do you know what I might be doing wrong?

**Comment by dhopp1** [comment]
Hi Julian, this is usually because one of your input variables doesn't have enough observations for the test/train split. It's on my list to A) give a better error message in this case and B) just fill those with 0 so that it doesn't throw the error. So go through and calculate out from at least what date you'd need observations for your train set, then see which variables don't have enough data for that. Remove them from the dataset then rerun and it should work. Hopefully that makes sense, let me know if it solves your issue. You can alternatively just run the code on increasing subsamples of input variables (killing the process if it works) until you find the variable(s) that break it. If you look at that/those then you'll probably see it/they have a shorter timeseries.

**Comment by JRSlotman** [comment]
Hi Daniel,

Thank you so much! That seems to be the issue, indeed. I added a line to my initialize_data function to drop all features for which the first observation is too close to the train end date (e.g. later than the median of the target observations). Removing these features alone already improves performance, but the feature_selection function also works like a charm now.

If I can make a suggestion for improvement, it would be to include an option in the feature_selection function to recognize those features that don't have sufficient coverage (also accounting for the init_test_size parameter) and eliminate them before running the calculations. Those features would never be among the best features anyway.

**Comment by dhopp1** [comment]
Yes that's a good idea, added to the to do list.

**Comment by dhopp1** [comment]
@JRSlotman Hi Julian, I added the discussed functionality. Now it will work regardless if there are columns with not enough data. Those columns will just not be able to be selected. In a normal model you can also see if there are any columns without data by running `model$no_data_cols`. This should be a big quality of life improvement because you no longer have to do the work yourself to exclude columns with not enough data coverage, it will be handled for you. So you really should be able to just throw any dataset at the model and it will always estimate for you. 

You have to update your Python version of the library to 0.2.4 by running `pip install --upgrade nowcast_lstm==0.2.4`. Since this was a purely backend change, there was no change to the R wrapper.
