### ISSUE TITLE
Error in system2(command = python, args = shQuote(script), stdout = TRUE,  : '"C:/Users/.../AppData/Local/r-miniconda"' not found

### ISSUE THREAD

**Issue by JRSlotman** [dhopp1/nowcastLSTM#8]
Hi Daniel,

I ran into some trouble trying to update the nowcastLSTM package and now I cannot get my code to work again. Specifically, the `use_python(python = miniconda_path(), required = T)` command gives the error in the title:
```
Error in system2(command = python, args = shQuote(script), stdout = TRUE,  : 
  '"C:/Users/jrslo/AppData/Local/r-miniconda"' not found
```
I tried updating R and all the relevant packages but I am afraid this only made matters worse. sessionInfo() shows that version 0.0.0.0000 of the nowcastLSTM package is loaded. I got the following warning `WARNING: Rtools is required to build R packages, but is not currently installed.` when trying to install the nowcastLSTM package through the install_github command.

I don't know if this is related but I changed the commands to load packages when trying to clean up my code. I wanted to use the librarian package as follows: `librarian::shelf(here, tidyverse, dhopp1/nowcastLSTM, beepr, furrr)` but this may have had some unintended consequences.

Any idea what I can do?

**Comment by dhopp1** [comment]
Yeah these broader environment questions are tough. The first thing I would do is just test reticulate out by itself, making sure reticulate and your python environment are working. Then if it is, you can move on to the nowcastLSTM library itself, removing reinstalling, etc.

But the "Rtools is not installed" error from `install_github` makes me think it might be a wider issue with your environment. Try installing another package with `install_github` and see if it works. If it doesn't, then the issue probably isn't with nowcastLSTM. One other last thing to keep in mind is making sure also the python nowcast_lstm version is updated to the latest version. Though this shouldn't affect anything, you would just get a library-specific error when you tried to run one of the new R functions which aren't in your python version.

One last tip I'd give is if you find yourself sinking a ton of time trying to figure out these errors, to not be afraid to simply reinstall your R and Python from scratch. You'll reinstall libraries as you find you need them, and that whole process can often take a fraction of the time the troubleshooting can take, and you'll end up with a much cleaner environment in the end.

**Comment by JRSlotman** [comment]
I must say this really feels like sinking time into this issue. I tried uninstalling Miniconda, R, RStudio and removing all associated folders before reinstalling. I now fail to install even the Python packages with `py_install(conda=miniconda_path(), "dill numpy pandas pmdarima torch nowcast-lstm", pip=TRUE)`, which results in the following error:
```
Error in conda_binary(conda) : 
  Supplied path is not a conda binary: ‘C:/Users/julian.slotman/AppData/Local/r-miniconda’
```

I checked the Python configuration with `py_config()`, which gave the following output
```
python:         C:/Users/julian.slotman/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/julian.slotman/AppData/Local/r-miniconda/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/julian.slotman/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/julian.slotman/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.22.3
```

How do I get this to work again?

**Comment by dhopp1** [comment]
What I would do (just skip to the next if you already tried):

-try leaving conda blank and having it find it automatically
-uninstall miniconda with `miniconda_uninstall(path = miniconda_path())`, reinstall it and try the install again
-if miniconda newly installed, but `py_install` giving same error, try `options(reticulate.conda_binary = miniconda_path())`, then `library(reticulate)`, etc.
-try all the same but using `conda_binary()` instead of `miniconda_path()`

I don't know what time zone you're in, but tomorrow from 10am CET to 6pm CET I could jump on a short call with you to see what's up, these path and environment things are usually simpler that way.

**Comment by dhopp1** [comment]
The last thing I would recommend, because it seems like from the beginning the issue has been all about the miniconda installation handled by reticulate, issues with paths etc., is to simply ignore it and leave it as it, and install Python normally as anyone wanting to use Python would. Follow the normal Python install instructions with pip for the libraries, then simply point your reticulate and `initialize_session()` funtions to use that Python installation.

There are plenty of guides on installing Python on Windows and installing packages, e.g., [installing python](https://phoenixnap.com/kb/how-to-install-python-3-windows), [installing packages](https://www.activestate.com/resources/quick-reads/python-package-installation-on-windows/).

**Comment by JRSlotman** [comment]
I managed to solve it, although I encountered a new issue which I will report separately. The issue really seems to have been with the Python path, with reticulate using another python as default (C:\Users\jrslo\AppData\Local\Microsoft\WindowsApps\python.exe), as found when running `Sys.which("python")`. I tailored the Python package installation and the initialize_session as follows:
```
Sys.setenv(RETICULATE_PYTHON = paste(miniconda_path(),"/python.exe", sep = ""))
py_install(as.list(strsplit("dill numpy pandas pmdarima torch nowcast-lstm", " ")[[1]]), pip = TRUE, conda = conda_binary())
initialize_session(paste(miniconda_path(),"/python.exe", sep = "")) 

```
I double checked on another device and it seems to work.
