### ISSUE TITLE
Failure to update to v0.2.0

### ISSUE THREAD

**Issue by JRSlotman** [dhopp1/nowcastLSTM#9]
Hi Daniel,

I tried updating the nowcastLSTM package to the latest version using the install_github command. However, `packageVersion("nowcastLSTM")` gives
`[1] ‘0.0.0.0’`. As a consequence, the new functions like hyperparameter tuning and variable selection are not found.

Specifying the release with `install_github("dhopp1/nowcastLSTM@v0.2.0")` gives the following error
`Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/dhopp1/nowcastLSTM/tarball/v0.2.0'`

Updating the Python package through `py_install(conda=miniconda_path(), "nowcast-lstm", pip=TRUE)` gives `Requirement already satisfied: nowcast-lstm in c:\users\julian.slotman\appdata\local\r-miniconda\lib\site-packages (0.2.1)`.

What to do?

**Comment by JRSlotman** [comment]
I finally managed to update and use the new functions by installing Rtools and reinstalling the nowcastLSTM package. Strangely, the command `packageVersion("nowcastLSTM")` still gives `[1] ‘0.0.0.0’ ` but at least I can use the new functions now.

**Comment by dhopp1** [comment]
Sorry I missed this the first time, the initial failure was because there is no 0.2.0 for the R version. I don't version the R wrapper, only the Python package. The R wrapper is backwards compatible with older versions of the Python package. Any time the Python package is updated, you need to update your Python package, then rerun the `install_github` command for R. I should make this clearer in the README for `nowcastLSTM`
